# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expense.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexpense.proto\x12\x07\x65xpense\"!\n\x0e\x45xpenseRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\"\n\x0f\x45xpenseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\x0e\x45xpenseService\x12?\n\nGetExpense\x12\x17.expense.ExpenseRequest\x1a\x18.expense.ExpenseResponseb\x06proto3')



_EXPENSEREQUEST = DESCRIPTOR.message_types_by_name['ExpenseRequest']
_EXPENSERESPONSE = DESCRIPTOR.message_types_by_name['ExpenseResponse']
ExpenseRequest = _reflection.GeneratedProtocolMessageType('ExpenseRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSEREQUEST,
  '__module__' : 'expense_pb2'
  # @@protoc_insertion_point(class_scope:expense.ExpenseRequest)
  })
_sym_db.RegisterMessage(ExpenseRequest)

ExpenseResponse = _reflection.GeneratedProtocolMessageType('ExpenseResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSERESPONSE,
  '__module__' : 'expense_pb2'
  # @@protoc_insertion_point(class_scope:expense.ExpenseResponse)
  })
_sym_db.RegisterMessage(ExpenseResponse)

_EXPENSESERVICE = DESCRIPTOR.services_by_name['ExpenseService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXPENSEREQUEST._serialized_start=26
  _EXPENSEREQUEST._serialized_end=59
  _EXPENSERESPONSE._serialized_start=61
  _EXPENSERESPONSE._serialized_end=95
  _EXPENSESERVICE._serialized_start=97
  _EXPENSESERVICE._serialized_end=178
# @@protoc_insertion_point(module_scope)
